name: Python Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run UI tests
        run: |
          pytest page_object_pattern/tests -v --alluredir=reports

      - name: Upload UI Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-allure-results
          path: reports

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run API tests
        run: |
          pytest api_tests/tests -v --alluredir=reports

      - name: Upload API Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-allure-results
          path: reports